"""Protobuf/Connect codec for the Grok Bot backend.

Builds a ``descriptor_pool`` at import time from ``descriptors.json``
(generated by ``tools/gen_grokbot_descriptors.mjs`` against the fork's
generated protobuf-es runtimes) and exposes encode/decode helpers plus
Connect-protocol framing.
"""

from __future__ import annotations

import json
import re
import struct
from pathlib import Path

from google.protobuf import (
    descriptor_pb2,
    descriptor_pool,
    json_format,
    message_factory,
)

_DESCRIPTORS_PATH = Path(__file__).with_name("descriptors.json")

_SCALAR_TYPES = {
    "double": descriptor_pb2.FieldDescriptorProto.TYPE_DOUBLE,
    "float": descriptor_pb2.FieldDescriptorProto.TYPE_FLOAT,
    "int64": descriptor_pb2.FieldDescriptorProto.TYPE_INT64,
    "uint64": descriptor_pb2.FieldDescriptorProto.TYPE_UINT64,
    "int32": descriptor_pb2.FieldDescriptorProto.TYPE_INT32,
    "fixed64": descriptor_pb2.FieldDescriptorProto.TYPE_FIXED64,
    "fixed32": descriptor_pb2.FieldDescriptorProto.TYPE_FIXED32,
    "bool": descriptor_pb2.FieldDescriptorProto.TYPE_BOOL,
    "string": descriptor_pb2.FieldDescriptorProto.TYPE_STRING,
    "bytes": descriptor_pb2.FieldDescriptorProto.TYPE_BYTES,
    "uint32": descriptor_pb2.FieldDescriptorProto.TYPE_UINT32,
    "sfixed32": descriptor_pb2.FieldDescriptorProto.TYPE_SFIXED32,
    "sfixed64": descriptor_pb2.FieldDescriptorProto.TYPE_SFIXED64,
    "sint32": descriptor_pb2.FieldDescriptorProto.TYPE_SINT32,
    "sint64": descriptor_pb2.FieldDescriptorProto.TYPE_SINT64,
}


def _json_name(local_name: str | None, proto_name: str) -> str:
    if local_name:
        return local_name
    parts = proto_name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _camel(name: str) -> str:
    return "".join(p.capitalize() for p in name.split("_"))


class _Tree:
    """Holds nested type definitions for one .proto file."""

    def __init__(self, name: str, package: str) -> None:
        self.proto = descriptor_pb2.FileDescriptorProto(
            name=name, package=package, syntax="proto3")
        self.nodes: dict[tuple[str, ...],
                         descriptor_pb2.DescriptorProto] = {}
        self.enum_nodes: dict[tuple[str, ...],
                              descriptor_pb2.EnumDescriptorProto] = {}

    def message(self, path: tuple[str, ...]) -> descriptor_pb2.DescriptorProto:
        if path in self.nodes:
            return self.nodes[path]
        desc = descriptor_pb2.DescriptorProto(name=path[-1])
        self.nodes[path] = desc
        if len(path) == 1:
            self.proto.message_type.add().CopyFrom(desc)
            self.nodes[path] = self.proto.message_type[-1]
        else:
            parent = self.message(path[:-1])
            parent.nested_type.add().CopyFrom(desc)
            self.nodes[path] = parent.nested_type[-1]
        return self.nodes[path]

    def enum(self, path: tuple[str, ...]) -> descriptor_pb2.EnumDescriptorProto:
        if path in self.enum_nodes:
            return self.enum_nodes[path]
        desc = descriptor_pb2.EnumDescriptorProto(name=path[-1])
        if len(path) == 1:
            self.proto.enum_type.add().CopyFrom(desc)
            self.enum_nodes[path] = self.proto.enum_type[-1]
        else:
            parent = self.message(path[:-1])
            parent.enum_type.add().CopyFrom(desc)
            self.enum_nodes[path] = parent.enum_type[-1]
        return self.enum_nodes[path]


def _map_entry_name(field_name: str) -> str:
    return f"{_camel(field_name)}Entry"


def _build_file(
        file_name: str, package: str,
        msg_names: list[str], enum_names: list[str],
        messages: dict, enums: dict) -> descriptor_pb2.FileDescriptorProto:
    tree = _Tree(file_name, package)
    prefix = f"{package}."

    for type_name in enum_names:
        rel = type_name[len(prefix):]
        tree.enum(tuple(rel.split(".")))

    for type_name in msg_names:
        rel = type_name[len(prefix):]
        path = tuple(rel.split("."))
        desc = tree.message(path)
        spec = messages[type_name]
        oneof_names: list[str] = []
        for f in spec["fields"]:
            if f.get("oneof") and f["oneof"] not in oneof_names:
                oneof_names.append(f["oneof"])
        for name in oneof_names:
            desc.oneof_decl.add(name=name)
        for f in spec["fields"]:
            fd = desc.field.add()
            fd.name = f["name"]
            fd.number = f["no"]
            fd.json_name = _json_name(f.get("localName"), f["name"])
            fd.label = (descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED
                        if f.get("repeated")
                        else descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL)
            if f.get("oneof") is not None:
                fd.oneof_index = oneof_names.index(f["oneof"])
            kind = f["kind"]
            if kind == "scalar":
                fd.type = _SCALAR_TYPES[f["T"]]
            elif kind == "enum":
                fd.type = descriptor_pb2.FieldDescriptorProto.TYPE_ENUM
                fd.type_name = f".{f['T']}"
            elif kind == "message":
                fd.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
                fd.type_name = f".{f['T']}"
            elif kind == "map":
                fd.type = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
                entry_name = _map_entry_name(f["name"])
                entry_path = path + (entry_name,)
                entry = tree.message(entry_path)
                entry.options.map_entry = True
                fd.type_name = "." + type_name + "." + entry_name
                spec_t = f["T"]
                kf = entry.field.add()
                kf.name, kf.number, kf.label, kf.json_name = (
                    "key", 1,
                    descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL, "key")
                kf.type = _SCALAR_TYPES[spec_t["key"]]
                vf = entry.field.add()
                vf.name, vf.number, vf.label, vf.json_name = (
                    "value", 2,
                    descriptor_pb2.FieldDescriptorProto.LABEL_OPTIONAL, "value")
                vkind = spec_t.get("valueKind", "scalar")
                if vkind == "message":
                    vf.type = (descriptor_pb2.FieldDescriptorProto
                               .TYPE_MESSAGE)
                    vf.type_name = f".{spec_t['value']}"
                elif vkind == "enum":
                    vf.type = descriptor_pb2.FieldDescriptorProto.TYPE_ENUM
                    vf.type_name = f".{spec_t['value']}"
                else:
                    vf.type = _SCALAR_TYPES[spec_t["value"]]

    for type_name in enum_names:
        rel = type_name[len(prefix):]
        desc = tree.enum(tuple(rel.split(".")))
        spec = enums[type_name]
        for value in spec["values"]:
            v = desc.value.add()
            v.name = value["name"]
            v.number = value["no"]
    return tree.proto


def _package_of(file_name: str, type_names: list[str]) -> str:
    # protobuf package matches the directory layout (aiserver/v1 -> aiserver.v1)
    return file_name.rsplit("/", 1)[0].replace("/", ".")


class GrokBotCodec:
    def __init__(self, descriptors_path: Path = _DESCRIPTORS_PATH) -> None:
        data = json.loads(descriptors_path.read_text())
        self.messages = data["messages"]
        self.enums = data["enums"]
        self.services = {s["typeName"]: s["methods"]
                         for s in data["services"]}

        files: dict[str, dict] = {}
        enum_files: dict[str, str] = {}
        for type_name, spec in self.messages.items():
            if spec.get("file") is None:
                continue
            files.setdefault(spec["file"], {"messages": [], "enums": []})
            files[spec["file"]]["messages"].append(type_name)
        for type_name, spec in self.enums.items():
            file_name = spec.get("file")
            if file_name is None:
                continue
            enum_files[type_name] = file_name
            if file_name not in files:
                files[file_name] = {"messages": [], "enums": []}
            files[file_name]["enums"].append(type_name)

        self.pool = descriptor_pool.DescriptorPool()
        # well-known google.protobuf types used by the generated protos
        for mod in ("struct_pb2", "timestamp_pb2", "empty_pb2"):
            wkt = __import__(f"google.protobuf.{mod}", fromlist=["DESCRIPTOR"])
            self.pool.AddSerializedFile(
                wkt.DESCRIPTOR.serialized_pb)
        pending = dict(files)
        resolved: set[str] = set()
        last_count = -1
        # iterate until every file's dependencies are added
        while pending and len(resolved) != last_count:
            last_count = len(resolved)
            for file_name in list(pending):
                type_names = (pending[file_name]["messages"]
                              + pending[file_name]["enums"])
                package = _package_of(file_name, type_names)
                deps = set()
                for tn in pending[file_name]["messages"]:
                    for f in self.messages[tn]["fields"]:
                        for ref in self._field_refs(f):
                            if ref.startswith("google.protobuf."):
                                continue
                            ref_file = self._type_file(ref, files, enum_files)
                            if ref_file and ref_file != file_name:
                                deps.add(ref_file)
                if any(d not in resolved for d in deps):
                    continue
                proto = _build_file(
                    file_name, package, pending[file_name]["messages"],
                    pending[file_name]["enums"], self.messages, self.enums)
                self.pool.Add(proto)
                resolved.add(file_name)
                del pending[file_name]
        if pending:
            raise RuntimeError(
                f"unresolved proto dependencies: {sorted(pending)}")
        self._classes: dict[str, type] = {}

    @staticmethod
    def _field_refs(f: dict) -> list[str]:
        if f["kind"] in ("message", "enum"):
            return [f["T"]]
        if (f["kind"] == "map"
                and f["T"].get("valueKind") == "message"):
            return [f["T"]["value"]]
        return []

    @staticmethod
    def _type_file(type_name: str, files: dict, enum_files: dict) -> str | None:
        for file_name, groups in files.items():
            if type_name in groups["messages"]:
                return file_name
        return enum_files.get(type_name)

    def message_class(self, type_name: str):
        if type_name not in self._classes:
            descriptor = self.pool.FindMessageTypeByName(type_name)
            self._classes[type_name] = message_factory.GetMessageClass(
                descriptor)
        return self._classes[type_name]

    def new(self, type_name: str, **kwargs):
        return self.message_class(type_name)(**kwargs)

    def decode(self, type_name: str, payload: bytes):
        msg = self.message_class(type_name)()
        if payload:
            msg.ParseFromString(payload)
        return msg

    def encode(self, msg) -> bytes:
        return msg.SerializeToString()


_CODEC: GrokBotCodec | None = None


def codec() -> GrokBotCodec:
    global _CODEC
    if _CODEC is None:
        _CODEC = GrokBotCodec()
    return _CODEC


# ── Connect protocol ────────────────────────────────────────────────

CONNECT_HTTP_STATUS = {
    "cancelled": 499, "unknown": 500, "invalid_argument": 400,
    "deadline_exceeded": 504, "not_found": 404, "already_exists": 409,
    "permission_denied": 403, "resource_exhausted": 429,
    "failed_precondition": 400, "aborted": 409, "out_of_range": 400,
    "unimplemented": 501, "internal": 500, "unavailable": 503,
    "data_loss": 500, "unauthenticated": 401,
}


class ConnectError(Exception):
    def __init__(self, code: str, message: str = "") -> None:
        super().__init__(message)
        self.code = code
        self.message = message

    @property
    def status(self) -> int:
        return CONNECT_HTTP_STATUS.get(self.code, 500)

    def body(self) -> dict:
        return {"code": self.code, "message": self.message}


def connect_envelope(payload: bytes, flag: int = 0) -> bytes:
    return struct.pack(">BI", flag, len(payload)) + payload


def end_stream_envelope(error: ConnectError | None = None) -> bytes:
    trailer: dict = {}
    if error is not None:
        trailer["error"] = error.body()
    return connect_envelope(
        json.dumps(trailer).encode(), flag=0x02)


def parse_envelope(body: bytes) -> bytes:
    """Extract the single request payload from a connect-stream body."""
    if len(body) >= 5:
        flag = body[0]
        size = struct.unpack(">I", body[1:5])[0]
        if flag == 0 and 5 + size <= len(body):
            return body[5:5 + size]
    return body


_METHOD_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")


def lookup_method(service_name: str, method_name: str):
    """Return (service_type_name, method_spec) or None. Accepts either the
    bare service name or the fully-qualified ``pkg.Service`` form."""
    if not _METHOD_NAME_RE.match(method_name):
        return None
    for type_name, methods in codec().services.items():
        if type_name != service_name \
                and type_name.split(".")[-1] != service_name:
            continue
        for spec in methods.values():
            if spec["name"] == method_name:
                return type_name, spec
    return None


def is_streaming(method_spec: dict) -> bool:
    kind = method_spec.get("kind")
    return kind in (1, "1", "SERVER_STREAMING", 3, "3", "BIDI_STREAMING")


def to_json_dict(msg) -> dict:
    return json_format.MessageToDict(
        msg, preserving_proto_field_name=True)


def from_json_dict(type_name: str, data: dict):
    msg = codec().message_class(type_name)()
    json_format.ParseDict(data, msg, ignore_unknown_fields=True)
    return msg
